### ISSUE TITLE
pkg-resources version

### ISSUE THREAD

**Issue by farhadcuber** [leobago/shardSim#1]
In `requirements.txt`:
`pkg-resources==0.0.0`
gives error:
`Collecting pkg-resources==0.0.0 (from -r requirements.txt (line 8))
  ERROR: Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from -r requirements.txt (line 8)) (from versions: none)
ERROR: No matching distribution found for pkg-resources==0.0.0 (from -r requirements.txt (line 8))`

**Comment by farhadcuber** [comment]
> In `requirements.txt`:
> `pkg-resources==0.0.0`
> gives error:
> `Collecting pkg-resources==0.0.0 (from -r requirements.txt (line 8)) ERROR: Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from -r requirements.txt (line 8)) (from versions: none) ERROR: No matching distribution found for pkg-resources==0.0.0 (from -r requirements.txt (line 8))`

this is a bug caused by ubuntu : [https://github.com/pypa/pip/issues/4022](url)
removing `pkg-resources==0.0.0` from `requirements.txt` solves the issue.

**Comment by leobago** [comment]
PR merged, thanks for your interest!
